// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package hn_gql

type Story struct {
	ID           string `json:"id"`
	Score        int    `json:"score"`
	URL          string `json:"url"`
	Title        string `json:"title"`
	CommentCount int    `json:"commentCount"`
}
